SELECT TITLE,
       UGR.BOARD_ID,
       REPLY_ID,
       UGR.WRITER_ID,
       UGR.CONTENTS,
       DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_REPLY AS UGR
         JOIN USED_GOODS_BOARD AS UGB ON UGR.BOARD_ID = UGB.BOARD_ID
WHERE UGB.CREATED_DATE >= '2022-10-01'
  AND UGB.CREATED_DATE < '2022-11-01'
ORDER BY UGR.CREATED_DATE, UGB.TITLE